# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config


# With remote theme
remote_theme: pzfreo/chulapa


# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale                  :     #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
repository              : pzfreo/chelli-site
title                   : Chelli Strings     #default["repository_name"]
title_separator         :     #default [" | "]
subtitle                : Handcrafted stringed instruments from Sussex    #default [your-repository-tagline]
description             : The website of Chelli Strings. Handcrafted string instruments in Chichester. Viola da Gamba, Viol, Viols, Baroque, Guitars, Folk instruments    #default [your-repository-tagline]
url                     : https://www.chellistrings.co.uk/    #See baseurl - On Github Pages you may leave it blank - If you use CNAME use your domain
baseurl                 :     #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
words_per_minute        :     #default[200]
timezone                :     #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# SEO
og_image                :  "./assets/images/scroll.jpg"   #default[author.avatar (see below)] or [github-avatar]
twitter_site            :     #Avoid @
author:
  name                  :     Paul Fremantle # Name Surname Company
  avatar                :     https://github.com/pzfreo.png
  location              :     Chichester, UK # New York, USA
  links:
    - url: https://instagram.com/paulfremantleluthier
      icon: fa fa-instagram
      label: instagram
  
fa_version: #default ["6"] Use 6 or 5
fa_kit_code: # Your FontAwesome kit code. If not provided a free hosted version (slower) will be loaded:  https://fontawesome.com/
fa_v4_support: #Bool Add FontAwesome 4 support
# Web tracking - Google services https://analytics.google.com/analytics/web/
# gtag_id is the preferred option, see https://developers.google.com/analytics/devguides/collection/gtagjs/migration?hl=en
# analytics provided for backwards compatibility
gtag_id                 :   G-J1J8NQZY8L
# analytics_id            :



# B. Navigation
# Configure your navbar and the footer of your site

# Navbar:
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     :  #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   : Chelli Strings # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  # An small image, try 30x30px
  nav:
  - title   : About # Label
    url     : /about # url
  - title   : Gallery # Label submenu
    child:
     - title: <span class="font-weight-bold">Gallery Home</span>
       url  : /gallery
     - title: Violin # Child label
       url  : /gallery/violin # child url
     - title: Terz Guitar # Child label
       url  : /gallery/terz # child url
     - title: Steel String Guitar
       url  : /gallery/gsmini
  - title   : Contact Us 
    url     : /contact
  - title   : Blog
    url     : /blog
    

#Social links to be placed on your site footer
footer:
  links:
    - label : Instagram #Label
      icon  : fab fa-instagram # Fontawesome 5 icon
      url   : https://www.instagram.com/paulfremantleluthier # A link or email: https://twitter.com/jack, mail@example.com
  copyright: # default is © <year> <name>

# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 # - url : # 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

# Theme and colors
chulapa-skin: 
  skin   : towards


# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
# paginate: 4
# paginate_path: "/blog/page:num/"
# paginator_maxnum: 3  #default[3] Custom: max of number to be displayed on the paginator


# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
# collections_dir:  .
# collections:
#   posts:
#     output: true
#     permalink : /blog/:year:month:day_:title

# future: true
# unpublished: true

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout            : "landingpage"
      include_on_feed   : true
      show_date         : true
      show_related      : true
      # show_bottomnavs   : true
      # show_sociallinks  : true
      # show_comments     : true
      # show_tags         : true
      # show_categories   : true
      # show_author       : true
      show_toc          : false
  


# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - /docs # ignore Chulapa /docs
  - /test # ignore Chulapa /test
  - github-metrics.svg

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

